name: Checkbox example
on:
  workflow_dispatch:
    inputs:
      test:
        description: "Enable this feature? test"
        required: false
        default: true
        type: boolean
      test1:
        description: "Enable this feature? test1"
        required: false
        default: true
        type: boolean

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Show checkbox value
        run: echo "Checkbox selected. test"
  test1:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Run only if checked
        if: ${{github.event.inputs.test1 ==true}}
        run: echo "checkbox was selected! test1"


