name: Checkbox example
on:
  workflow_dispatch:
    input:
      test:
        description: "Enable this feature? test"
        required: false
        defalut: true
        type: boolean
      test1:
        description: "Enable this feature? test1"
        required: false
        defalut: true
        type: boolean

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Show checkbox value
        run: echo "Checkbox selected. ${{github.event.inputs.my_checkbox}}"
  test1:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Run only if checked
        if: ${{github.event.inputs.my_checkbox ==true}}
        run: echo "checkbox was selected! $MY_CHECKBOX"


